import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useState } from "react";
import Header from "@/front/components/templates/header";
import Modal from "@/front/components/base/modal";
import ReportModal from "@/front/components/templates/reportModal";
import SquadsHomePage from "@/front/components/templates/squadsHomePage";
import EmployeesHomePage from "@/front/components/templates/employeesHomePage";

export default function Home() {
  const [selectedTab, setSelectedTab] = useState("squads");
  const [reportModal, setReportModal] = useState(false);

  function handleSelectTab(tab: string) {
    setSelectedTab(tab);
  }

  function handleShowReportModal() {
    setReportModal(true);
  }

  return (
    <>
      <Head>
        <title>PD Soluções</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        {reportModal && (
          <Modal
            onClose={() => setReportModal(false)}
            modalName="Criar lançamento"
          >
            <ReportModal closeModalProps={() => setReportModal(false)} />
          </Modal>
        )}
        <Header
          selectedTab={selectedTab}
          onSelectTab={handleSelectTab}
          showReportModal={handleShowReportModal}
        />
        <div className={styles.homepage}>
          {selectedTab === "squads" && <SquadsHomePage />}
          {selectedTab === "users" && <EmployeesHomePage />}
        </div>
      </main>
    </>
  );
}
