import Head from "next/head";
import { Roboto } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useState } from "react";
import Header from "@/front/components/templates/header";

const roboto = Roboto({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
});

export default function Home() {

  const [selectedTab, setSelectedTab] = useState("squads");

  function handleSelectTab(tab: string) {
    setSelectedTab(tab);
  }

  function handleShowReportModal() {
    console.log("open modal");
  }
  
  return (
    <>
      <Head>
        <title>PD Soluções</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${roboto.className}`}>
        <Header
          selectedTab={selectedTab}
          onSelectTab={handleSelectTab}
          showReportModal={handleShowReportModal}
        />
        <div className={styles.homepage}>

        </div>
      </main>
    </>
  );
}
